/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.binxin.zdapp.activity;

public final class R {
    public static final class anim {
        public static final int push_left_in=0x7f040000;
        public static final int push_left_out=0x7f040001;
    }
    public static final class array {
        public static final int app=0x7f060009;
        public static final int database=0x7f06000e;
        public static final int excel=0x7f06000b;
        public static final int fileEndingAudio=0x7f060004;
        public static final int fileEndingImage=0x7f060003;
        public static final int fileEndingPackage=0x7f060005;
        public static final int fileEndingVideo=0x7f060007;
        public static final int fileEndingWebText=0x7f060006;
        public static final int hexadecimal=0x7f060001;
        public static final int hexadecimal2=0x7f060002;
        public static final int pdf=0x7f06000d;
        public static final int ppt=0x7f06000c;
        public static final int spnner=0x7f060000;
        public static final int textfile=0x7f060008;
        public static final int word=0x7f06000a;
    }
    public static final class attr {
    }
    public static final class color {
        /** 蜜色 
         */
        public static final int aliceblue=0x7f07002c;
        /** 亚麻色 
         */
        public static final int antiquewhite=0x7f070022;
        /** 中灰兰色 
         */
        public static final int aqua=0x7f070087;
        /** 粟色 
         */
        public static final int aquamarine=0x7f070068;
        /** 沙褐色 
         */
        public static final int azure=0x7f07002a;
        /** 烟白色 
         */
        public static final int beige=0x7f070027;
        /** 浅玫瑰色 
         */
        public static final int bisque=0x7f07000d;
        /** 海军色 
         */
        public static final int black=0x7f070096;
        /** 番木色 
         */
        public static final int blanchedalmond=0x7f07000b;
        /** 暗绿色 
         */
        public static final int blue=0x7f070092;
        /** 暗红色 
         */
        public static final int blueviolet=0x7f07005b;
        /** 暗灰色 
         */
        public static final int brown=0x7f070050;
        public static final int btn_text_colors=0x7f0700a2;
        public static final int btn_ver_text=0x7f0700a3;
        /** 亮青色 
         */
        public static final int burlywood=0x7f070034;
        /** 菊兰色 
         */
        public static final int cadetblue=0x7f070076;
        /** 碧绿色 
         */
        public static final int chartreuse=0x7f070069;
        /** 茶色 
         */
        public static final int chocolate=0x7f07003f;
        /** 暗桔黄色 
         */
        public static final int coral=0x7f070017;
        /** 中绿色 
         */
        public static final int cornflowerblue=0x7f070075;
        /** 柠檬绸色 
         */
        public static final int cornsilk=0x7f070007;
        /** 淡灰色 
         */
        public static final int crimson=0x7f070037;
        /** 黑色 
         */
        public static final int cyan=0x7f070097;
        /** 青蓝色 
         */
        public static final int cyan2=0x7f070098;
        /** 中兰色 
         */
        public static final int darkblue=0x7f070094;
        /** 深天蓝色 
         */
        public static final int darkcyan=0x7f07008e;
        /** 中粉紫色 
         */
        public static final int darkgoldenrod=0x7f070047;
        /** 亮蓝色 
         */
        public static final int darkgray=0x7f07004e;
        /** 绿色 
         */
        public static final int darkgreen=0x7f070091;
        /** 暗灰色 
         */
        public static final int darkgrey=0x7f07004f;
        /** 银色 
         */
        public static final int darkkhaki=0x7f070044;
        /** 重褐色 
         */
        public static final int darkmagenta=0x7f070059;
        /** 军兰色 
         */
        public static final int darkolivegreen=0x7f070077;
        /** 亮肉色 
         */
        public static final int darkorange=0x7f070016;
        /** 赭色 
         */
        public static final int darkorchid=0x7f070052;
        /** 暗洋红 
         */
        public static final int darkred=0x7f07005a;
        /** 紫罗兰色 
         */
        public static final int darksalmon=0x7f070031;
        /** 亮绿色 
         */
        public static final int darkseagreen=0x7f070057;
        /** 中绿宝石 
         */
        public static final int darkslateblue=0x7f07007a;
        /** 橙绿色 
         */
        public static final int darkslategray=0x7f070080;
        /** 暗瓦灰色 
         */
        public static final int darkslategrey=0x7f070081;
        /** 中春绿色 
         */
        public static final int darkturquoise=0x7f07008c;
        /** 苍绿色 
         */
        public static final int darkviolet=0x7f070054;
        /** 红橙色 
         */
        public static final int deeppink=0x7f07001b;
        /** 暗宝石绿 
         */
        public static final int deepskyblue=0x7f07008d;
        /** 石蓝色 
         */
        public static final int dimgray=0x7f070072;
        /** 暗灰色 
         */
        public static final int dimgrey=0x7f070073;
        /** 亮海蓝色 
         */
        public static final int dodgerblue=0x7f070085;
        /** 暗金黄色 
         */
        public static final int firebrick=0x7f070048;
        /** 雪白色 
         */
        public static final int floralwhite=0x7f070005;
        /** 海绿色 
         */
        public static final int forestgreen=0x7f070083;
        /** 深粉红色 
         */
        public static final int fuchsia=0x7f07001c;
        /** 洋李色 
         */
        public static final int gainsboro=0x7f070036;
        /** 鲜肉色 
         */
        public static final int ghostwhite=0x7f070024;
        /** 桃色 
         */
        public static final int gold=0x7f070011;
        /** 苍紫罗兰色 
         */
        public static final int goldenrod=0x7f070039;
        /** 靓蓝
         */
        public static final int gray=0x7f070061;
        /** 水鸭色 
         */
        public static final int green=0x7f070090;
        /** 浅绿色 
         */
        public static final int greenq=0x7f070088;
        /** 苍宝石绿 
         */
        public static final int greenyellow=0x7f07004c;
        /** 灰色 
         */
        public static final int grey=0x7f070062;
        /** 灰色 
         */
        public static final int grey2=0x7f070063;
        /** 浅灰色
         */
        public static final int grey3=0x7f070064;
        /** 天蓝色 
         */
        public static final int honeydew=0x7f07002b;
        /** 珊瑚色 
         */
        public static final int hotpink=0x7f070018;
        public static final int ic_app_text=0x7f0700a4;
        /** 秘鲁色 
         */
        public static final int indianred=0x7f070041;
        /** 暗橄榄绿 
         */
        public static final int indigo=0x7f070078;
        /** 白色 
         */
        public static final int ivory=0x7f070001;
        /** 艾利斯兰 
         */
        public static final int khaki=0x7f07002d;
        /** 暗肉色 
         */
        public static final int lavender=0x7f070032;
        /** 海贝色 
         */
        public static final int lavenderblush=0x7f070009;
        /** 黄绿色 
         */
        public static final int lawngreen=0x7f07006a;
        /** 花白色 
         */
        public static final int lemonchiffon=0x7f070006;
        /** 旧的标题蓝色
         */
        public static final int lightBlue=0x7f070060;
        /** 黄绿色 
         */
        public static final int lightblue=0x7f07004d;
        /** 黄褐色 
         */
        public static final int lightcoral=0x7f07002e;
        /** 淡紫色 
         */
        public static final int lightcyan=0x7f070033;
        /** 老花色 
         */
        public static final int lightgoldenrodyellow=0x7f070020;
        /** 蓟色 
         */
        public static final int lightgray=0x7f07003c;
        /** 中紫色 
         */
        public static final int lightgreen=0x7f070056;
        /** 亮灰色 
         */
        public static final int lightgrey=0x7f07003d;
        /** 粉红色 
         */
        public static final int lightpink=0x7f070013;
        /** 橙色 
         */
        public static final int lightsalmon=0x7f070015;
        /** 森林绿 
         */
        public static final int lightseagreen=0x7f070084;
        /** 紫罗兰蓝色 
         */
        public static final int lightskyblue=0x7f07005c;
        /** 中暗蓝色 
         */
        public static final int lightslategray=0x7f07006c;
        /** 亮蓝灰 
         */
        public static final int lightslategrey=0x7f07006d;
        /** 粉蓝色 
         */
        public static final int lightsteelblue=0x7f07004a;
        /** 象牙色 
         */
        public static final int lightyellow=0x7f070002;
        /** 春绿色 
         */
        public static final int lime=0x7f07008a;
        /** 中海蓝 
         */
        public static final int limegreen=0x7f07007f;
        /** 亮金黄色 
         */
        public static final int linen=0x7f070021;
        /** 紫红色 
         */
        public static final int magenta=0x7f07001d;
        /** 紫色 
         */
        public static final int maroon=0x7f070067;
        /** 暗灰色 
         */
        public static final int mediumaquamarine=0x7f070074;
        /** 蓝色 
         */
        public static final int mediumblue=0x7f070093;
        /** 褐玫瑰红 
         */
        public static final int mediumorchid=0x7f070046;
        /** 暗紫罗兰色 
         */
        public static final int mediumpurple=0x7f070055;
        /** 青绿色 
         */
        public static final int mediumseagreen=0x7f07007e;
        /** 草绿色 
         */
        public static final int mediumslateblue=0x7f07006b;
        /** 酸橙色 
         */
        public static final int mediumspringgreen=0x7f07008b;
        /** 靛青色 
         */
        public static final int mediumturquoise=0x7f070079;
        /** 印第安红 
         */
        public static final int mediumvioletred=0x7f070042;
        /** 闪兰色 
         */
        public static final int midnightblue=0x7f070086;
        /** 幽灵白 
         */
        public static final int mintcream=0x7f070025;
        /** 白杏色 
         */
        public static final int mistyrose=0x7f07000c;
        /** 桔黄色 
         */
        public static final int moccasin=0x7f07000e;
        /** 鹿皮色 
         */
        public static final int navajowhite=0x7f07000f;
        /** 暗蓝色 
         */
        public static final int navy=0x7f070095;
        /** 红色 
         */
        public static final int oldlace=0x7f07001f;
        /** 白灰色
         */
        public static final int olive=0x7f070065;
        /** 灰石色 
         */
        public static final int olivedrab=0x7f070070;
        /** 亮粉红色 
         */
        public static final int orange=0x7f070014;
        /** 西红柿色 
         */
        public static final int orangered=0x7f07001a;
        /** 金麒麟色 
         */
        public static final int orchid=0x7f07003a;
        /** 亮珊瑚色 
         */
        public static final int palegoldenrod=0x7f07002f;
        /** 暗紫色 
         */
        public static final int palegreen=0x7f070053;
        /** 亮钢兰色 
         */
        public static final int paleturquoise=0x7f07004b;
        /** 暗深红色 
         */
        public static final int palevioletred=0x7f070038;
        /** 淡紫红 
         */
        public static final int papayawhip=0x7f07000a;
        /** 纳瓦白 
         */
        public static final int peachpuff=0x7f070010;
        /** 巧可力色 
         */
        public static final int peru=0x7f070040;
        /** 金色 
         */
        public static final int pink=0x7f070012;
        /** 实木色 
         */
        public static final int plum=0x7f070035;
        /** 火砖色 
         */
        public static final int powderblue=0x7f070049;
        /** 橄榄色 
         */
        public static final int purple=0x7f070066;
        public static final int qqappwall_half_transparent=0x7f0700a1;
        /**  <color name="qqappwall_textcolor_gray_press">#ffffffff</color>  
 #5bade8 
         */
        public static final int qqappwall_splitline_color=0x7f07009e;
        public static final int qqappwall_textblack=0x7f07009b;
        public static final int qqappwall_textcolor_black=0x7f07009f;
        public static final int qqappwall_textcolor_black_disable=0x7f0700a0;
        public static final int qqappwall_textcolor_gray=0x7f07009c;
        public static final int qqappwall_textcolor_gray_disable=0x7f07009d;
        public static final int qqappwall_textwhite=0x7f07009a;
        /** 红紫色 
         */
        public static final int red=0x7f07001e;
        /** 暗黄褐色 
         */
        public static final int rosybrown=0x7f070045;
        /** 钢兰色 
         */
        public static final int royalblue=0x7f07007c;
        /** 暗海兰色 
         */
        public static final int saddlebrown=0x7f070058;
        /** 古董白 
         */
        public static final int salmon=0x7f070023;
        /** 浅黄色 
         */
        public static final int sandybrown=0x7f070029;
        /** 米绸色 
         */
        public static final int seaShell=0x7f070008;
        /** 暗瓦灰色 
         */
        public static final int seagreen=0x7f070082;
        /** 褐色 
         */
        public static final int sienna=0x7f070051;
        /** 中紫罗兰色 
         */
        public static final int silver=0x7f070043;
        /** 亮天蓝色 
         */
        public static final int skyblue=0x7f07005d;
        /** 深绿褐色 
         */
        public static final int slateblue=0x7f070071;
        /** 亮蓝灰 
         */
        public static final int slategray=0x7f07006e;
        /** 灰石色 
         */
        public static final int slategrey=0x7f07006f;
        /** 黄色 
         */
        public static final int snow=0x7f070004;
        /** 青色 
         */
        public static final int springgreen=0x7f070089;
        /** 暗灰蓝色 
         */
        public static final int steelblue=0x7f07007b;
        /** 亮灰色 
         */
        public static final int tan=0x7f07003e;
        /** 暗青色 
         */
        public static final int teal=0x7f07008f;
        /** 淡紫色 
         */
        public static final int thistle=0x7f07003b;
        /** 天蓝色 
         */
        public static final int title=0x7f07005e;
        /** #4599FF标题蓝色
         */
        public static final int title_old=0x7f07005f;
        /** 热粉红色 
         */
        public static final int tomato=0x7f070019;
        /** 浅青蓝色
         */
        public static final int trans=0x7f070099;
        /** 皇家蓝 
         */
        public static final int turquoise=0x7f07007d;
        /** 苍麒麟色 
         */
        public static final int violet=0x7f070030;
        public static final int webview_text=0x7f0700a5;
        /** 米色 
         */
        public static final int wheat=0x7f070028;
        public static final int white=0x7f070000;
        /** 薄荷色 
         */
        public static final int whitesmoke=0x7f070026;
        /** 亮黄色 
         */
        public static final int yellow=0x7f070003;
    }
    public static final class dimen {
        public static final int qqappwall_software_icon_size=0x7f09000b;
        public static final int qqappwall_text_hsize=0x7f090002;
        public static final int qqappwall_text_lsize=0x7f090004;
        public static final int qqappwall_text_msize=0x7f090003;
        public static final int qqappwall_text_xsize=0x7f090001;
        /**  没用到 
         */
        public static final int qqappwall_text_xxsize=0x7f090000;
        public static final int qqappwall_textsize_b=0x7f090005;
        public static final int qqappwall_textsize_m=0x7f090007;
        public static final int qqappwall_textsize_s=0x7f090009;
        public static final int qqappwall_textsize_ss=0x7f09000a;
        public static final int qqappwall_textsize_xm=0x7f090006;
        public static final int qqappwall_textsize_xs=0x7f090008;
    }
    public static final class drawable {
        public static final int about=0x7f020000;
        public static final int addfolderr=0x7f020001;
        public static final int alert_dialog_icon=0x7f020002;
        public static final int audio=0x7f020003;
        public static final int background=0x7f020004;
        public static final int bg_about=0x7f020005;
        public static final int bg_about_bar=0x7f020006;
        public static final int bg_btn_about=0x7f020007;
        public static final int bg_btn_about_bar=0x7f020008;
        public static final int bg_btn_app=0x7f020009;
        public static final int bg_btn_close=0x7f02000a;
        public static final int bg_btn_edit=0x7f02000b;
        public static final int bg_btn_exit=0x7f02000c;
        public static final int bg_btn_fans=0x7f02000d;
        public static final int bg_btn_light=0x7f02000e;
        public static final int bg_btn_option=0x7f02000f;
        public static final int bg_btn_options=0x7f020010;
        public static final int bg_btn_popmenu=0x7f020011;
        public static final int bg_btn_search=0x7f020012;
        public static final int bg_btn_setting=0x7f020013;
        public static final int bg_btn_settings=0x7f020014;
        public static final int bg_btn_style=0x7f020015;
        public static final int bg_btn_title=0x7f020016;
        public static final int bg_btn_torch=0x7f020017;
        public static final int bg_btn_welview=0x7f020018;
        public static final int bg_btn_welviewc=0x7f020019;
        public static final int bg_smtxl=0x7f02001a;
        public static final int bgblack=0x7f02001b;
        public static final int bgblacksmall=0x7f02001c;
        public static final int btn_app_list=0x7f02001d;
        public static final int btn_close_default=0x7f02001e;
        public static final int btn_close_press=0x7f02001f;
        public static final int btn_pause=0x7f020020;
        public static final int btn_restart=0x7f020021;
        public static final int btn_second=0x7f020022;
        public static final int btn_seconds=0x7f020023;
        public static final int btn_start=0x7f020024;
        public static final int btn_stop=0x7f020025;
        public static final int calluser=0x7f020026;
        public static final int compass=0x7f020027;
        public static final int database=0x7f020028;
        public static final int default2=0x7f020029;
        public static final int delete=0x7f02002a;
        public static final int edituser=0x7f02002b;
        public static final int excel_icon=0x7f02002c;
        public static final int exit_main=0x7f02002d;
        public static final int file_refresh=0x7f02002e;
        public static final int folder=0x7f02002f;
        public static final int home=0x7f020030;
        public static final int ic_action_search=0x7f020031;
        public static final int ic_app=0x7f020032;
        public static final int ic_app_adress=0x7f020033;
        public static final int ic_app_bg=0x7f020034;
        public static final int ic_app_calculator=0x7f020035;
        public static final int ic_app_compass=0x7f020036;
        public static final int ic_app_files=0x7f020037;
        public static final int ic_app_hard=0x7f020038;
        public static final int ic_app_press=0x7f020039;
        public static final int ic_app_s1=0x7f02003a;
        public static final int ic_app_s2=0x7f02003b;
        public static final int ic_app_s3=0x7f02003c;
        public static final int ic_app_timer=0x7f02003d;
        public static final int ic_app_torch=0x7f02003e;
        public static final int ic_app_widget=0x7f02003f;
        public static final int ic_app_wifiap=0x7f020040;
        public static final int ic_edit_default=0x7f020041;
        public static final int ic_edit_press=0x7f020042;
        public static final int ic_icon=0x7f020043;
        public static final int ic_light_default=0x7f020044;
        public static final int ic_light_press=0x7f020045;
        public static final int ic_option_default=0x7f020046;
        public static final int ic_option_press=0x7f020047;
        public static final int ic_play=0x7f020048;
        public static final int ic_selected=0x7f020049;
        public static final int ic_serch_default=0x7f02004a;
        public static final int ic_serch_press=0x7f02004b;
        public static final int ic_stop=0x7f02004c;
        public static final int ic_torch_default=0x7f02004d;
        public static final int ic_torch_press=0x7f02004e;
        public static final int icon=0x7f02004f;
        public static final int image=0x7f020050;
        public static final int into_arr=0x7f020051;
        public static final int into_arr_a=0x7f020052;
        public static final int into_arr_in=0x7f020053;
        public static final int packed=0x7f020054;
        public static final int pased=0x7f020055;
        public static final int pdf_icon=0x7f020056;
        public static final int ppt_icon=0x7f020057;
        public static final int qqappwall_alert_dialog_bg=0x7f020058;
        public static final int qqappwall_appcenter_icon=0x7f020059;
        public static final int qqappwall_background_white=0x7f0200bb;
        public static final int qqappwall_btn_back_press=0x7f02005a;
        public static final int qqappwall_btn_close=0x7f02005b;
        public static final int qqappwall_home_frame_bg=0x7f02005c;
        public static final int qqappwall_home_list_above_selector=0x7f02005d;
        public static final int qqappwall_home_list_below_selector=0x7f02005e;
        public static final int qqappwall_home_list_devider=0x7f02005f;
        public static final int qqappwall_home_list_item_above=0x7f020060;
        public static final int qqappwall_home_list_item_above_press=0x7f020061;
        public static final int qqappwall_home_list_item_below=0x7f020062;
        public static final int qqappwall_home_list_item_below_press=0x7f020063;
        public static final int qqappwall_home_list_item_middle=0x7f020064;
        public static final int qqappwall_home_list_item_middle_press=0x7f020065;
        public static final int qqappwall_home_list_middle_selector=0x7f020066;
        public static final int qqappwall_icon_btn_list_bg=0x7f020067;
        public static final int qqappwall_icon_btn_list_download=0x7f020068;
        public static final int qqappwall_icon_btn_list_install=0x7f020069;
        public static final int qqappwall_icon_btn_list_launch=0x7f02006a;
        public static final int qqappwall_icon_btn_list_pause=0x7f02006b;
        public static final int qqappwall_icon_btn_list_update=0x7f02006c;
        public static final int qqappwall_inner_icon_cyclebtn=0x7f02006d;
        public static final int qqappwall_inner_icon_cyclebtn_press=0x7f02006e;
        public static final int qqappwall_input_box_bg=0x7f02006f;
        public static final int qqappwall_input_clear=0x7f020070;
        public static final int qqappwall_list_item_color_pressed=0x7f0200b8;
        public static final int qqappwall_main_background=0x7f0200b7;
        public static final int qqappwall_normal_list_selector=0x7f020071;
        public static final int qqappwall_overscroll_edge=0x7f020072;
        public static final int qqappwall_overscroll_glow=0x7f020073;
        public static final int qqappwall_progressbar_activity_waiting=0x7f020074;
        public static final int qqappwall_progressbar_waiting1=0x7f020075;
        public static final int qqappwall_progressbar_waiting10=0x7f020076;
        public static final int qqappwall_progressbar_waiting11=0x7f020077;
        public static final int qqappwall_progressbar_waiting12=0x7f020078;
        public static final int qqappwall_progressbar_waiting2=0x7f020079;
        public static final int qqappwall_progressbar_waiting3=0x7f02007a;
        public static final int qqappwall_progressbar_waiting4=0x7f02007b;
        public static final int qqappwall_progressbar_waiting5=0x7f02007c;
        public static final int qqappwall_progressbar_waiting6=0x7f02007d;
        public static final int qqappwall_progressbar_waiting7=0x7f02007e;
        public static final int qqappwall_progressbar_waiting8=0x7f02007f;
        public static final int qqappwall_progressbar_waiting9=0x7f020080;
        public static final int qqappwall_ratingbar_small=0x7f020081;
        public static final int qqappwall_scrollbar=0x7f020082;
        public static final int qqappwall_search_button=0x7f020083;
        public static final int qqappwall_search_button_bg=0x7f020084;
        public static final int qqappwall_search_button_bg_selected=0x7f020085;
        public static final int qqappwall_search_button_bg_selector=0x7f020086;
        public static final int qqappwall_search_input_left_icon=0x7f020087;
        public static final int qqappwall_selector_inner_icon_cyclebtn=0x7f020088;
        public static final int qqappwall_selector_textcolor_black=0x7f020089;
        public static final int qqappwall_selector_textcolor_gray=0x7f02008a;
        public static final int qqappwall_software_default_icon=0x7f02008b;
        public static final int qqappwall_software_icon_bg=0x7f02008c;
        public static final int qqappwall_star_small=0x7f02008d;
        public static final int qqappwall_star_small_gray=0x7f02008e;
        public static final int qqappwall_textgary=0x7f0200b9;
        public static final int qqappwall_topbar_search_btn_pressed=0x7f02008f;
        public static final int qqappwall_trans=0x7f0200ba;
        public static final int qqappwall_webview_title_bg=0x7f020090;
        public static final int sdcard=0x7f020091;
        public static final int selector=0x7f020092;
        public static final int selector_push=0x7f020093;
        public static final int sendsms=0x7f020094;
        public static final int temp_ad=0x7f020095;
        public static final int text=0x7f020096;
        public static final int ui_editext=0x7f020097;
        public static final int ui_menu_bg_bottom=0x7f020098;
        public static final int ui_menu_bg_bottom_pressed=0x7f020099;
        public static final int ui_menu_bg_center=0x7f02009a;
        public static final int ui_menu_bg_center_pressed=0x7f02009b;
        public static final int ui_menu_bg_top=0x7f02009c;
        public static final int ui_menu_bg_top_pressed=0x7f02009d;
        public static final int ui_menu_bottom=0x7f02009e;
        public static final int ui_menu_center=0x7f02009f;
        public static final int ui_menu_top=0x7f0200a0;
        public static final int ui_ti_text=0x7f0200a1;
        public static final int upfolder=0x7f0200a2;
        public static final int uponelevel=0x7f0200a3;
        public static final int vbea=0x7f0200a4;
        public static final int video=0x7f0200a5;
        public static final int view_back=0x7f0200a6;
        public static final int weather_none=0x7f0200a7;
        public static final int webtext=0x7f0200a8;
        public static final int welcome=0x7f0200a9;
        public static final int welcome_01=0x7f0200aa;
        public static final int welcome_02=0x7f0200ab;
        public static final int welcome_03=0x7f0200ac;
        public static final int welcome_04=0x7f0200ad;
        public static final int welcome_05=0x7f0200ae;
        public static final int welcome_06=0x7f0200af;
        public static final int welcome_frame_1=0x7f0200b0;
        public static final int welcome_frame_2=0x7f0200b1;
        public static final int welcome_frame_3=0x7f0200b2;
        public static final int welcome_frame_4=0x7f0200b3;
        public static final int welcome_frame_5=0x7f0200b4;
        public static final int word_icon=0x7f0200b5;
        public static final int zdapp=0x7f0200b6;
    }
    public static final class id {
        public static final int AnalogClock=0x7f0a011e;
        public static final int Base=0x7f0a0118;
        public static final int Button01=0x7f0a0047;
        public static final int ContactList=0x7f0a002f;
        public static final int Date=0x7f0a011a;
        public static final int EditText01=0x7f0a0033;
        public static final int EditText02=0x7f0a0036;
        public static final int EditText03=0x7f0a0039;
        public static final int EditText04=0x7f0a003f;
        public static final int EditText05=0x7f0a0042;
        public static final int EditText06=0x7f0a0045;
        public static final int EditText08=0x7f0a003c;
        public static final int EditText_PROM=0x7f0a004d;
        public static final int FrameLayout01=0x7f0a009f;
        public static final int Month=0x7f0a0119;
        public static final int RelativeLayout01=0x7f0a00a0;
        public static final int SearchHeadLayout=0x7f0a00c9;
        public static final int SmallBase=0x7f0a011c;
        public static final int SosoImageViewClose=0x7f0a00cc;
        public static final int TableRow01=0x7f0a0031;
        public static final int TableRow02=0x7f0a0034;
        public static final int TableRow03=0x7f0a0037;
        public static final int TableRow04=0x7f0a003d;
        public static final int TableRow05=0x7f0a0040;
        public static final int TableRow06=0x7f0a0043;
        public static final int TableRow07=0x7f0a0046;
        public static final int TableRow08=0x7f0a003a;
        public static final int TextTest1=0x7f0a0014;
        public static final int TextTest2=0x7f0a0013;
        public static final int TextView01=0x7f0a0032;
        public static final int TextView02=0x7f0a0035;
        public static final int TextView03=0x7f0a0038;
        public static final int TextView04=0x7f0a003e;
        public static final int TextView05=0x7f0a0041;
        public static final int TextView06=0x7f0a0044;
        public static final int TextView08=0x7f0a003b;
        public static final int TextView1=0x7f0a000f;
        public static final int TextView2=0x7f0a007b;
        public static final int TextView3=0x7f0a007a;
        public static final int TextView7=0x7f0a0063;
        public static final int TextView_Address=0x7f0a00f5;
        public static final int TextView_Blog=0x7f0a00f7;
        public static final int TextView_Email=0x7f0a00f6;
        public static final int TextView_Home=0x7f0a00f3;
        public static final int TextView_Mobile=0x7f0a00f2;
        public static final int TextView_Name=0x7f0a00f1;
        public static final int TextView_PROM=0x7f0a004c;
        public static final int TextView_qq=0x7f0a00f4;
        public static final int WeekDay=0x7f0a011b;
        public static final int Widget=0x7f0a011d;
        public static final int abt_abt=0x7f0a0006;
        public static final int abt_appscore=0x7f0a0008;
        public static final int abt_hist=0x7f0a0005;
        public static final int abt_new=0x7f0a0004;
        public static final int abt_syxy=0x7f0a000c;
        public static final int abt_t=0x7f0a000b;
        public static final int abt_vbea=0x7f0a0009;
        public static final int abt_web=0x7f0a000a;
        public static final int abt_welcome=0x7f0a0007;
        public static final int ad_container=0x7f0a0078;
        public static final int air_quailty=0x7f0a0103;
        public static final int app_widget=0x7f0a006a;
        public static final int app_wifiap=0x7f0a006c;
        public static final int aq_address=0x7f0a012f;
        public static final int aq_age=0x7f0a012e;
        public static final int aq_appfalse=0x7f0a0132;
        public static final int aq_appgood=0x7f0a0131;
        public static final int aq_apphope=0x7f0a0133;
        public static final int aq_appname=0x7f0a0130;
        public static final int aq_btn_male=0x7f0a012d;
        public static final int aq_gaijin=0x7f0a0134;
        public static final int aq_name=0x7f0a012c;
        public static final int aq_phone=0x7f0a0136;
        public static final int aq_submit=0x7f0a0137;
        public static final int aq_test=0x7f0a0138;
        public static final int aq_yijian=0x7f0a0135;
        public static final int btn01=0x7f0a005a;
        public static final int btn02=0x7f0a005c;
        public static final int btn02s=0x7f0a005b;
        public static final int btn03=0x7f0a005e;
        public static final int btn04=0x7f0a005f;
        public static final int btn08=0x7f0a0120;
        public static final int btnCloseAP=0x7f0a012a;
        public static final int btnConnectAP=0x7f0a0127;
        public static final int btnGetConnectedIP=0x7f0a0123;
        public static final int btnGetOwmId=0x7f0a0129;
        public static final int btnOpenAP=0x7f0a0125;
        public static final int btnSC=0x7f0a005d;
        public static final int btnScan=0x7f0a0121;
        public static final int btnSec=0x7f0a00eb;
        public static final int btnStartPaunse=0x7f0a00e9;
        public static final int btnStop=0x7f0a00ea;
        public static final int btn_close=0x7f0a0003;
        public static final int btn_colorlight=0x7f0a00ec;
        public static final int btn_colortorch=0x7f0a0072;
        public static final int btn_edit=0x7f0a00f0;
        public static final int btn_hardv=0x7f0a0060;
        public static final int btn_next=0x7f0a013e;
        public static final int btn_suggestion=0x7f0a0048;
        public static final int btn_title=0x7f0a0074;
        public static final int btn_torchcompass=0x7f0a002b;
        public static final int btn_welcome_in=0x7f0a0064;
        public static final int btn_welcome_out=0x7f0a0065;
        public static final int btn_wifiast=0x7f0a0122;
        public static final int btn_wifist=0x7f0a0126;
        public static final int button=0x7f0a00ed;
        public static final int calculator=0x7f0a006f;
        public static final int calculatorScreenTextView=0x7f0a0016;
        public static final int city_save_btn=0x7f0a00fb;
        public static final int compass=0x7f0a0069;
        public static final int compassimg=0x7f0a002c;
        public static final int compassimg2=0x7f0a002d;
        public static final int comt_surfaceview=0x7f0a002e;
        public static final int device_text_cpuhz=0x7f0a0052;
        public static final int device_text_cpumodel=0x7f0a0051;
        public static final int device_text_mac=0x7f0a0056;
        public static final int device_text_model=0x7f0a004f;
        public static final int device_text_ontime=0x7f0a0058;
        public static final int device_text_ram=0x7f0a0054;
        public static final int device_text_rom=0x7f0a0053;
        public static final int device_text_sclv=0x7f0a0057;
        public static final int device_text_sdcard=0x7f0a0055;
        public static final int device_text_ver=0x7f0a0050;
        public static final int downloadlabel=0x7f0a0002;
        public static final int ed_led=0x7f0a0015;
        public static final int edit_text=0x7f0a0030;
        public static final int filename=0x7f0a0010;
        public static final int files=0x7f0a0066;
        public static final int general_software_list_item=0x7f0a00ce;
        public static final int hard=0x7f0a006d;
        public static final int id0=0x7f0a006b;
        public static final int image_refresh=0x7f0a0100;
        public static final int intoWeixin=0x7f0a00ef;
        public static final int layout_install_btn=0x7f0a00d1;
        public static final int layout_relativeapp_detail=0x7f0a00ab;
        public static final int light=0x7f0a0068;
        public static final int light_layout=0x7f0a0070;
        public static final int light_layout2=0x7f0a0073;
        public static final int light_title=0x7f0a0071;
        public static final int linearLayout7=0x7f0a00ca;
        public static final int list_item=0x7f0a00cf;
        public static final int mButton1=0x7f0a0029;
        public static final int mButton10=0x7f0a001d;
        public static final int mButton11=0x7f0a0022;
        public static final int mButton12=0x7f0a001e;
        public static final int mButton13=0x7f0a001a;
        public static final int mButton14=0x7f0a0026;
        public static final int mButton15=0x7f0a002a;
        public static final int mButton16=0x7f0a0028;
        public static final int mButton17=0x7f0a0017;
        public static final int mButton18=0x7f0a0018;
        public static final int mButton19=0x7f0a0019;
        public static final int mButton2=0x7f0a0023;
        public static final int mButton21=0x7f0a0027;
        public static final int mButton3=0x7f0a0024;
        public static final int mButton4=0x7f0a0025;
        public static final int mButton5=0x7f0a001f;
        public static final int mButton6=0x7f0a0020;
        public static final int mButton7=0x7f0a0021;
        public static final int mButton8=0x7f0a001b;
        public static final int mButton9=0x7f0a001c;
        public static final int main_img_page=0x7f0a0077;
        public static final int menu_settings=0x7f0a0141;
        public static final int message_content_send=0x7f0a004a;
        public static final int opt_about=0x7f0a0082;
        public static final int opt_bxastudy=0x7f0a007f;
        public static final int opt_calculator=0x7f0a00e6;
        public static final int opt_editpsdsm=0x7f0a00e2;
        public static final int opt_exit=0x7f0a0083;
        public static final int opt_fankui=0x7f0a0080;
        public static final int opt_help=0x7f0a0081;
        public static final int opt_joke=0x7f0a007e;
        public static final int opt_myapp=0x7f0a00e5;
        public static final int opt_offpsdsm=0x7f0a00e3;
        public static final int opt_onpsdsm=0x7f0a00e7;
        public static final int opt_setApplication=0x7f0a00e1;
        public static final int opt_setBluetooth=0x7f0a00de;
        public static final int opt_setDevelopment=0x7f0a00e0;
        public static final int opt_setNetwork=0x7f0a00dd;
        public static final int opt_setTime=0x7f0a00df;
        public static final int opt_setting=0x7f0a00dc;
        public static final int opt_settings=0x7f0a007d;
        public static final int opt_torch=0x7f0a00e4;
        public static final int pagertab=0x7f0a0076;
        public static final int parent=0x7f0a000d;
        public static final int playbutton=0x7f0a0011;
        public static final int pm25_text=0x7f0a0102;
        public static final int progressBar=0x7f0a0115;
        public static final int psd_btn01=0x7f0a0086;
        public static final int psd_btn02=0x7f0a0087;
        public static final int psd_btn03=0x7f0a008d;
        public static final int psd_btn04=0x7f0a008b;
        public static final int psd_edit01=0x7f0a0084;
        public static final int psd_edit02=0x7f0a0085;
        public static final int psd_edit03=0x7f0a008c;
        public static final int psd_edit04=0x7f0a0088;
        public static final int psd_edit05=0x7f0a0089;
        public static final int psd_edit06=0x7f0a008a;
        public static final int qq_app_wall_view=0x7f0a000e;
        public static final int qq_update_sdk_negetive_button=0x7f0a0091;
        public static final int qq_update_sdk_new_feature=0x7f0a008e;
        public static final int qq_update_sdk_positive_button=0x7f0a0090;
        public static final int qq_update_sdk_support=0x7f0a008f;
        public static final int qqappwall_8cell_app0=0x7f0a00ac;
        public static final int qqappwall_8cell_app1=0x7f0a00af;
        public static final int qqappwall_8cell_app2=0x7f0a00b2;
        public static final int qqappwall_8cell_app3=0x7f0a00b5;
        public static final int qqappwall_8cell_app4=0x7f0a00b8;
        public static final int qqappwall_8cell_app5=0x7f0a00bb;
        public static final int qqappwall_8cell_app6=0x7f0a00be;
        public static final int qqappwall_8cell_app7=0x7f0a00c1;
        public static final int qqappwall_8cell_app_icon0=0x7f0a00ad;
        public static final int qqappwall_8cell_app_icon1=0x7f0a00b0;
        public static final int qqappwall_8cell_app_icon2=0x7f0a00b3;
        public static final int qqappwall_8cell_app_icon3=0x7f0a00b6;
        public static final int qqappwall_8cell_app_icon4=0x7f0a00b9;
        public static final int qqappwall_8cell_app_icon5=0x7f0a00bc;
        public static final int qqappwall_8cell_app_icon6=0x7f0a00bf;
        public static final int qqappwall_8cell_app_icon7=0x7f0a00c2;
        public static final int qqappwall_8cell_app_name0=0x7f0a00ae;
        public static final int qqappwall_8cell_app_name1=0x7f0a00b1;
        public static final int qqappwall_8cell_app_name2=0x7f0a00b4;
        public static final int qqappwall_8cell_app_name3=0x7f0a00b7;
        public static final int qqappwall_8cell_app_name4=0x7f0a00ba;
        public static final int qqappwall_8cell_app_name5=0x7f0a00bd;
        public static final int qqappwall_8cell_app_name6=0x7f0a00c0;
        public static final int qqappwall_8cell_app_name7=0x7f0a00c3;
        public static final int qqappwall_advert_btn_remove=0x7f0a00aa;
        public static final int qqappwall_advert_img=0x7f0a00a9;
        public static final int qqappwall_app_detail_appname=0x7f0a0094;
        public static final int qqappwall_app_detail_btn_down=0x7f0a009e;
        public static final int qqappwall_app_detail_close=0x7f0a009a;
        public static final int qqappwall_app_detail_description=0x7f0a009c;
        public static final int qqappwall_app_detail_dialog=0x7f0a0092;
        public static final int qqappwall_app_detail_feedesc=0x7f0a0097;
        public static final int qqappwall_app_detail_icon=0x7f0a0093;
        public static final int qqappwall_app_detail_progress=0x7f0a009d;
        public static final int qqappwall_app_detail_scroll=0x7f0a009b;
        public static final int qqappwall_app_detail_size=0x7f0a0096;
        public static final int qqappwall_app_detail_soft_icon=0x7f0a0099;
        public static final int qqappwall_app_detail_star=0x7f0a0095;
        public static final int qqappwall_id_tag_viewHolder=0x7f0a0000;
        public static final int qqappwall_layout_main_ad_bar=0x7f0a00a8;
        public static final int qqappwall_listitem_appname=0x7f0a00d5;
        public static final int qqappwall_listitem_btn_download=0x7f0a00d2;
        public static final int qqappwall_listitem_btn_download_label=0x7f0a00d3;
        public static final int qqappwall_listitem_icon=0x7f0a00d0;
        public static final int qqappwall_listitem_size=0x7f0a00d7;
        public static final int qqappwall_listitem_star=0x7f0a00d6;
        public static final int qqappwall_listwait_TextView01=0x7f0a00a2;
        public static final int qqappwall_listwait_WaitingBtn=0x7f0a00a3;
        public static final int qqappwall_listwait_progressbar01=0x7f0a00a1;
        public static final int qqappwall_main_top_bar=0x7f0a00a5;
        public static final int qqappwall_product_list=0x7f0a00a6;
        public static final int qqappwall_search_bar=0x7f0a00c7;
        public static final int qqappwall_searchbar_btn_back=0x7f0a00c8;
        public static final int qqappwall_searchbar_img_search=0x7f0a00cd;
        public static final int qqappwall_searchbar_input=0x7f0a00cb;
        public static final int qqappwall_text=0x7f0a00a7;
        public static final int qqappwall_topbar_btn_back=0x7f0a00c6;
        public static final int qqappwall_topbar_img_search=0x7f0a00c5;
        public static final int qqappwall_webview_root=0x7f0a00a4;
        public static final int result=0x7f0a0128;
        public static final int sc_end=0x7f0a013f;
        public static final int sc_restar=0x7f0a0140;
        public static final int sc_star=0x7f0a00d8;
        public static final int scrollView04=0x7f0a0079;
        public static final int scrollView09=0x7f0a0062;
        public static final int send_button_send=0x7f0a004b;
        public static final int smtxl=0x7f0a0067;
        public static final int software_first_line_info=0x7f0a00d4;
        public static final int software_second_line_info=0x7f0a0098;
        public static final int ssd=0x7f0a00ff;
        public static final int star_image01=0x7f0a0139;
        public static final int star_image02=0x7f0a013a;
        public static final int star_image03=0x7f0a013b;
        public static final int star_image04=0x7f0a013c;
        public static final int star_image05=0x7f0a013d;
        public static final int stopbutton=0x7f0a0012;
        public static final int surfaceview=0x7f0a00ee;
        public static final int telNumText_send=0x7f0a0049;
        public static final int temp_q=0x7f0a0101;
        public static final int temp_q_text1=0x7f0a0107;
        public static final int temp_q_text2=0x7f0a010b;
        public static final int temp_q_text3=0x7f0a010f;
        public static final int temp_q_text4=0x7f0a0113;
        public static final int textView4=0x7f0a007c;
        public static final int textWelcome=0x7f0a0116;
        public static final int textsensor=0x7f0a00d9;
        public static final int textsensor2=0x7f0a00db;
        public static final int textsensor3=0x7f0a00da;
        public static final int timer=0x7f0a006e;
        public static final int title=0x7f0a004e;
        public static final int title_text=0x7f0a00c4;
        public static final int today_message=0x7f0a00fa;
        public static final int tvTime=0x7f0a00e8;
        public static final int viewholder=0x7f0a0001;
        public static final int viewpager=0x7f0a0075;
        public static final int weather_city_text=0x7f0a00fd;
        public static final int weather_image=0x7f0a00fc;
        public static final int weather_image1=0x7f0a0105;
        public static final int weather_image2=0x7f0a0109;
        public static final int weather_image3=0x7f0a010d;
        public static final int weather_image4=0x7f0a0111;
        public static final int weather_layout=0x7f0a00f8;
        public static final int weather_temp=0x7f0a00fe;
        public static final int weather_text1=0x7f0a0106;
        public static final int weather_text2=0x7f0a010a;
        public static final int weather_text3=0x7f0a010e;
        public static final int weather_text4=0x7f0a0112;
        public static final int weather_title_layout=0x7f0a00f9;
        public static final int weather_view=0x7f0a0114;
        public static final int webView1=0x7f0a0061;
        public static final int webView3=0x7f0a0117;
        public static final int week1=0x7f0a0104;
        public static final int week2=0x7f0a0108;
        public static final int week3=0x7f0a010c;
        public static final int week4=0x7f0a0110;
        public static final int welcome_img=0x7f0a012b;
        public static final int widget0=0x7f0a0059;
        public static final int widget_tor=0x7f0a011f;
        public static final int wifiip=0x7f0a0124;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int activity_view_demo=0x7f030001;
        public static final int app_smtxl=0x7f030002;
        public static final int audiotest=0x7f030003;
        public static final int bxa=0x7f030004;
        public static final int calculator=0x7f030005;
        public static final int compass=0x7f030006;
        public static final int comtorch=0x7f030007;
        public static final int contacts=0x7f030008;
        public static final int editorcontacts=0x7f030009;
        public static final int fankui=0x7f03000a;
        public static final int file_dialog=0x7f03000b;
        public static final int file_rename=0x7f03000c;
        public static final int hard_device=0x7f03000d;
        public static final int hardware=0x7f03000e;
        public static final int help=0x7f03000f;
        public static final int history=0x7f030010;
        public static final int ic_vbea_zdapp_1=0x7f030011;
        public static final int ic_vbea_zdapp_2=0x7f030012;
        public static final int ic_vbea_zdapp_3=0x7f030013;
        public static final int ic_vbea_zdapp_4=0x7f030014;
        public static final int ic_vbea_zdapp_5=0x7f030015;
        public static final int ic_vbea_zdapp_6=0x7f030016;
        public static final int ic_vbea_zdapp_7=0x7f030017;
        public static final int ic_zdapp_1=0x7f030018;
        public static final int ic_zdapp_2=0x7f030019;
        public static final int light=0x7f03001a;
        public static final int lightcolor=0x7f03001b;
        public static final int main=0x7f03001c;
        public static final int more=0x7f03001d;
        public static final int options=0x7f03001e;
        public static final int password=0x7f03001f;
        public static final int password_edit=0x7f030020;
        public static final int password_off=0x7f030021;
        public static final int qq_update_sdk_dialog=0x7f030022;
        public static final int qqappwall_layout_detail_dialog=0x7f030023;
        public static final int qqappwall_layout_list_waiting=0x7f030024;
        public static final int qqappwall_layout_main=0x7f030025;
        public static final int qqappwall_layout_main_ad_bar=0x7f030026;
        public static final int qqappwall_layout_main_software_cell=0x7f030027;
        public static final int qqappwall_layout_main_top_bar=0x7f030028;
        public static final int qqappwall_layout_search=0x7f030029;
        public static final int qqappwall_layout_search_bar=0x7f03002a;
        public static final int qqappwall_layout_software_list_item=0x7f03002b;
		public static final int scale=0x7f03003b;
        public static final int scrcolor=0x7f03002c;
        public static final int sensor=0x7f03002d;
        public static final int setings=0x7f03002e;
        public static final int settings=0x7f03002f;
        public static final int softsyxy=0x7f030030;
        public static final int timer=0x7f030031;
        public static final int torch=0x7f030032;
        public static final int vbeatelier=0x7f030033;
        public static final int viewuser=0x7f030034;
        public static final int weather_main=0x7f030035;
        public static final int welcome=0x7f030036;
        public static final int widget_6_0=0x7f030037;
        public static final int widget_layout=0x7f030038;
        public static final int widget_layout_small=0x7f030039;
        public static final int widget_time=0x7f03003a;
        public static final int widget_torch=0x7f03003b;
        public static final int wifiap=0x7f03003c;
        public static final int zdapp=0x7f03003d;
        public static final int zdapp_aq=0x7f03003e;
    }
    public static final class menu {
        public static final int activity_demo=0x7f0c0000;
        public static final int activity_view_pager_demo=0x7f0c0001;
    }
    public static final class string {
        public static final int about=0x7f080020;
        public static final int aboutzdapp=0x7f080071;
        public static final int abt=0x7f080056;
        public static final int add_user=0x7f080031;
        public static final int address=0x7f080038;
        public static final int app_name=0x7f08001f;
        public static final int app_torch=0x7f08002a;
        public static final int appscore=0x7f08006b;
        public static final int audiotest=0x7f080046;
        public static final int blog=0x7f08003a;
        public static final int btn_download=0x7f08001c;
        public static final int btn_install=0x7f080019;
        public static final int btn_start=0x7f08001a;
        public static final int btn_update=0x7f08001b;
        public static final int btn_waiting=0x7f08001d;
        public static final int bxa=0x7f080022;
        public static final int calculator=0x7f080029;
        public static final int call_user=0x7f08003d;
        public static final int cancel=0x7f08002d;
        public static final int checkNewVer=0x7f080066;
        public static final int compass=0x7f080027;
        public static final int comtorch=0x7f080028;
        public static final int current_dir=0x7f080025;
        public static final int date=0x7f08005e;
        public static final int date_small=0x7f08005f;
        public static final int delete_user=0x7f08003b;
        public static final int demo3d=0x7f08004b;
        public static final int device=0x7f080069;
        public static final int editor_user=0x7f080032;
        public static final int email=0x7f080039;
        public static final int eula_accept=0x7f080042;
        public static final int eula_refuse=0x7f080043;
        public static final int eula_title=0x7f080041;
        public static final int exit=0x7f08002e;
        public static final int f_lose=0x7f080054;
        public static final int f_sending=0x7f080052;
        public static final int f_success=0x7f080053;
        public static final int fankui=0x7f080051;
        public static final int filename=0x7f080047;
        public static final int filenoexist=0x7f08004a;
        public static final int files=0x7f080026;
        public static final int h_3dtest=0x7f08004c;
        public static final int hardtest=0x7f08002b;
        public static final int hello=0x7f08001e;
        public static final int help=0x7f080021;
        public static final int history=0x7f080055;
        public static final int home=0x7f080036;
        public static final int init_time_100millisecond=0x7f080063;
        public static final int init_time_second=0x7f080062;
        public static final int joke=0x7f08005d;
        public static final int l_3dtest=0x7f08004d;
        public static final int light=0x7f08003f;
        public static final int menu_about=0x7f08006d;
        public static final int menu_exit=0x7f08006e;
        public static final int menu_setting_100milisec=0x7f080065;
        public static final int menu_setting_second=0x7f080064;
        public static final int menu_setting_timer_unit=0x7f08006c;
        public static final int menu_settings=0x7f080023;
        public static final int mobile=0x7f080035;
        public static final int mymblog=0x7f08005a;
        public static final int myweb=0x7f080058;
        public static final int name=0x7f080034;
        public static final int ok=0x7f08002c;
        public static final int playbutton=0x7f080048;
        public static final int qq=0x7f080037;
        public static final int qq_update_sdk_cancel=0x7f080008;
        public static final int qq_update_sdk_check_update_failed=0x7f080009;
        public static final int qq_update_sdk_download_failed=0x7f08000c;
        public static final int qq_update_sdk_download_failed_to_retry=0x7f08000d;
        public static final int qq_update_sdk_download_finish=0x7f08000a;
        public static final int qq_update_sdk_download_finish_to_install=0x7f08000b;
        public static final int qq_update_sdk_exit=0x7f080004;
        public static final int qq_update_sdk_next=0x7f080003;
        public static final int qq_update_sdk_no=0x7f080006;
        public static final int qq_update_sdk_retry=0x7f080007;
        public static final int qq_update_sdk_support_info=0x7f08000e;
        public static final int qq_update_sdk_update=0x7f080002;
        public static final int qq_update_sdk_update_dialog_title=0x7f080001;
        public static final int qq_update_sdk_yes=0x7f080005;
        public static final int qqappwall_anctivity_waitinfo=0x7f080012;
        public static final int qqappwall_input_search=0x7f08000f;
        public static final int qqappwall_listwait_getmore=0x7f080013;
        public static final int qqappwall_loading=0x7f080017;
        public static final int qqappwall_main_title=0x7f080010;
        public static final int qqappwall_network_not_available=0x7f080011;
        public static final int qqappwall_notify_download_failed=0x7f080016;
        public static final int qqappwall_notify_download_finished=0x7f080015;
        public static final int qqappwall_notify_downloading=0x7f080014;
        public static final int qqappwall_notify_net_error=0x7f080018;
        public static final int revert=0x7f08003c;
        public static final int save=0x7f08002f;
        public static final int scrtest=0x7f08004f;
        public static final int scrtorch=0x7f080050;
        public static final int sendsms_user=0x7f08003e;
        public static final int sensor=0x7f080068;
        public static final int sm_password=0x7f08006a;
        public static final int smtxl=0x7f080030;
        public static final int stopbutton=0x7f080049;
        public static final int syxy=0x7f080057;
        public static final int syxy2=0x7f080059;
        public static final int timer=0x7f080061;
        public static final int torch=0x7f080040;
        public static final int up_one_level=0x7f080024;
        public static final int vbea=0x7f08005b;
        public static final int vbea_Copyright=0x7f080073;
        public static final int vbea_lx=0x7f08005c;
        public static final int view_user=0x7f080033;
        public static final int welcomepage=0x7f080067;
        public static final int widget2013=0x7f08004e;
        public static final int widget_name=0x7f080060;
        public static final int wifiap=0x7f080044;
        public static final int wifiapp=0x7f080045;
        public static final int zdapp_anq=0x7f080072;
        public static final int zdapphistory=0x7f080000;
        public static final int zdappsyxy=0x7f08006f;
        public static final int zdappsyxy2=0x7f080070;
    }
    public static final class style {
        public static final int AppBlack=0x7f0b000c;
        /** <item name="android:windowTitleColor">@style/TitleColor</item
         */
        public static final int AppLight=0x7f0b000f;
        public static final int AppTheme=0x7f0b000b;
        public static final int ND=0x7f0b0012;
        public static final int NT=0x7f0b0010;
        public static final int NTD=0x7f0b0011;
        public static final int NoTitle=0x7f0b000d;
        public static final int NoTitleF=0x7f0b0013;
        /** <item name="android:TitleColor">@color/title</item>
         */
        public static final int TitleColor=0x7f0b000e;
        public static final int qqappwall_RatingBar_small=0x7f0b0000;
        public static final int qqappwall_dialog=0x7f0b0009;
        public static final int qqappwall_half_transparent=0x7f0b000a;
        public static final int qqappwall_progressBar_activity_wait=0x7f0b0008;
        public static final int qqappwall_textstyle_m_black=0x7f0b0004;
        public static final int qqappwall_textstyle_m_gray=0x7f0b0002;
        public static final int qqappwall_textstyle_s_gray=0x7f0b0006;
        public static final int qqappwall_textstyle_safe=0x7f0b0007;
        public static final int qqappwall_textstyle_ss_gray=0x7f0b0003;
        public static final int qqappwall_textstyle_xm_black=0x7f0b0005;
        public static final int qqappwall_textstyle_xs_gray=0x7f0b0001;
    }
    public static final class xml {
        public static final int colors_b_w=0x7f050000;
        public static final int colors_b_w_b=0x7f050001;
        public static final int colors_black=0x7f050002;
        public static final int colors_blue=0x7f050003;
        public static final int colors_com_blue=0x7f050004;
        public static final int colors_com_green=0x7f050005;
        public static final int colors_com_red=0x7f050006;
        public static final int colors_fuchsia=0x7f050007;
        public static final int colors_green=0x7f050008;
        public static final int colors_grey=0x7f050009;
        public static final int colors_lightblue=0x7f05000a;
        public static final int colors_red=0x7f05000b;
        public static final int colors_w_b=0x7f05000c;
        public static final int colors_w_b_w=0x7f05000d;
        public static final int colors_white=0x7f05000e;
        public static final int colors_yellow=0x7f05000f;
        public static final int end=0x7f050010;
        public static final int torch=0x7f050011;
        public static final int widget=0x7f050012;
        public static final int widget_small=0x7f050013;
        public static final int widget_time=0x7f050014;
    }
}
